### ISSUE TITLE
[Orbetto]: Using JLinkGDBServer for daisy chained chip setup

### ISSUE THREAD

**Issue by wico-merkel** [Auterion/embedded-debug-tools#6]
### **Setup:**
* Custom board with a STM32H7 connected in a daisy chain running latest px4-autopilot firmware
* JLink Base connected with JTag_SWD Pins to custom board
* JlinkGDBServer started with [-jtagconf](https://wiki.segger.com/J-Link_GDB_Server#-jtagconf) command

### **Problem Description:**
I am trying to get the tracing output on a custom flight controller board running a version of the px4-autopilot code. The documentation only mentions the[ --jlink and --stlink option, but not the --remote](https://github.com/Auterion/embedded-debug-tools/tree/main/ext/orbetto#capture). Since I am having a daisy chained MCU, I need to use the --remote with JLinkGDBServer to setup my JTAG scan chain (at least I do not know how to do it otherwise). So one terminal runs the JLinkGDBServer and another one gdb:
`% python3 -m emdbg.bench.fmu --target cubepilot_cubeorange_default --remote localhost:2331`

Now I run into the following two issues:

**Problem 1:**
![image](https://github.com/Auterion/embedded-debug-tools/assets/108858856/c5cb99f1-7488-4bec-991b-4ab3458beb6d)
I think I entered [this function](https://github.com/Auterion/embedded-debug-tools/blob/main/src/emdbg/debug/data/cortex_m.gdb#L192) and px4_reset is not defined in this context. If I manually add the px4_reset, identical to the one in[ jlink.gdb](https://github.com/Auterion/embedded-debug-tools/blob/main/src/emdbg/debug/data/jlink.gdb#L4), I run into the second issue.

**Problem 2:**
![image](https://github.com/Auterion/embedded-debug-tools/assets/108858856/1b23c0ad-4db5-4586-899d-af8b0f2543dc) I think we are never reaching the [breakpoint nx_start](https://github.com/Auterion/embedded-debug-tools/blob/main/src/emdbg/debug/data/cortex_m.gdb#L211) since the reset did not work correctly. 

Is there a way to get this working for the "--remote" option as well? Or are we limited here to the --jlink or --stlink version? 

---

I also have some general question regarding the setup, I hope this is the right place for them too.

![image](https://github.com/Auterion/embedded-debug-tools/assets/108858856/fa000582-0222-49f0-a410-80929e07504e)

As far as I understand, replacing the ORBTrace with a JLink Base or any other debugger should not have a impact as long as the JTDO pin is connected to it, e.g. this means the [nostalgic Cube Orange Flight Controllers
](https://docs.px4.io/main/en/flight_controller/cubepilot_cube_orange.html) would not be supported, since they only have the [mini debug port](http://docs.px4.io/main/en/debug/swd_debug.html#pixhawk-debug-mini). But with the SWD port we only have the 4kB FIFO buffer for our tracing data. Is that correct? 

And I also wonder if the software differentiates between the different output options (big red circle, SWD vs SWO). The [command used only mentions enable trace](https://github.com/Auterion/embedded-debug-tools/blob/main/src/emdbg/debug/data/cortex_m.gdb#L153), am I correct that both tracing options work in parallel?

Thanks for you help in advance. I am looking forward to get this tool working and giving it a test run. 

Regards, 
Kevin

**Comment by wico-merkel** [comment]
TBD

**Comment by niklaut** [comment]
The issue is that the default `px4_reset` implementation tries to reset via the RESET pin, which is probably not connected on your board. You can use `monitor reset 0` instead, which will use the [internal software reset](https://wiki.segger.com/J-Link_Reset_Strategies#Strategies_for_Cortex-M_devices).

> Is there a way to get this working for the "--remote" option as well? Or are we limited here to the --jlink or --stlink version?

`monitor reset` has different syntax for OpenOCD and JLink, thus we would have to automatically detect what we're connected to. Perhaps over the port number?

> But with the SWD port we only have the 4kB FIFO buffer for our tracing data.

Yes, but reading that buffer is not implemented in hardware in any debug probe (like RTT on the JLink), so polling that in software would be too slow to make sense on the STM32H7. 

If you can somehow get at pin PB3, you get at least SWO out, which will give you 90% of the benefit already. Your JLink Base also supports SWO input up to 30Mbps, which is quite reasonable, so you don't need a ORBTrace.
